# Generated by `mix grpc.gen`.
# DO NOT EDIT!

defmodule Hello.Hello.Service do
  use GRPC.Service, name: "hello.Hello"

  rpc :Hello, Hello.HelloRequest, Hello.HelloReply
end

defmodule Hello.Hello.Stub do
  use GRPC.Stub, service: Hello.Hello.Service
end

defmodule Hello do
  use Protobuf, """
syntax = "proto3";
package hello;

service Hello {
  rpc Hello(HelloRequest) returns (HelloReply) {}
} 

message HelloRequest {
  string name = 1;
}
message HelloReply {
  string message = 1;
}
  """
end
